add dialog function
opxica/modular-ui-widgetbook pull request #2
Opened 2024-01-14 16:36 UTC by hrxmanek

added dialog tab in modular_ui

2024-01-14 16:36 UTC, hrxmanek commented
hope my first try went well

2024-01-14 16:49 UTC, omjogani requested changes
Please remove` .vscode` folder from the PR. Other things seems good to me!

2024-01-14 16:49 UTC, omjogani commented on .vscode/settings.json
Remove this file by adding it to `.gitignore`

2024-01-15 14:38 UTC, omjogani approved these changes
LGTM!

2024-01-15 14:38 UTC, omjogani commented
Thanks for your contribution @hrxmanek 🚀

2024-01-15 14:38 UTC, merged

2024-01-15 16:26 UTC, hrxmanek commented
> Thanks for your contribution @hrxmanek 🚀

thankful for the opportunity 😊👍